### PR TITLE
2533: Filter changes (store tab and role details)

### LINKED ISSUE #2533: Filter changes (store tab and role details)
1. When we remember our filters, we need to remember which tab they relate to.   

Steps to reproduce:
* log in as blue player
* leave the `Own forces` filters empty
* set a `Type` filter for `Other Forces`
* refresh the page.  See the filter is applied to own forces

I suspect we need to introduce multiple `filter` cookies, that include the name of the tab.  From within the `PlanningAssets` component, the `opFor` boolean flag can be used to determine if it is the `Own Forces` or `Other Forces` tab.

2.  When we remember Support Panel preferences, remember the role they related to.

Steps to reproduce:
* log in as `Adjudicator 1`
* select `Adjudiction` tab
* switch to `Blue` user
* note the app opens with the `Adjudication` tab open - which should not happen

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #2533

### CODE REVIEW

File: packages/components/src/local/organisms/planning-channel/index.tsx [hunk 1]
```diff
@@ -765,11 +765,15 @@ export const PlanningChannel: React.FC<PropTypes> = ({
   }
 
   const onSupportPanelLayoutChange = (key: string, value: string) => {
```
Comment (IanMayo) [inline packages/components/src/local/organisms/planning-channel/index.tsx:767]: hello @philb89 :-) 
I Iike the new strategy, but can we make the key "support.planning.[rolename]", then we just call the children "filterApplied", "supportPanelWidth" and "visibleColumns".

Comment (lebaphi) [reply packages/components/src/local/organisms/planning-channel/index.tsx:767]: sure Ian 👍🏻

**Review by IanMayo — APPROVED** [review]
