### PR TITLE
Handle undefined Force role name

### LINKED ISSUE #1144: Force role name update create undefined
## 🐞 Bug description

Create Wargame > Select Force > Roles > Add Role > Select Role name > Press Delete button > Role name will be undefined

## 🖥️ Screenshots

https://user-images.githubusercontent.com/16476120/133719804-256516d0-328d-40f9-91e9-d488f3d58083.mov

## 💻 System information

 - Operating System: [e.g. iOS, Windows, etc...]
 - Browser Version [e.g. 22]
 - Browser resolution 
 - Are cookies enabled
 - Is Javascript enabled
 - Do you have an ad blocker

### PR DESCRIPTION
**Pull request by sanjayradadiya**
## 🧰 Issue

Fixes #1144 

## 🔨Work carried out:

- [x] Tests pass

## 🖥️ Screenshot

https://user-images.githubusercontent.com/16476120/134115533-f2ad2819-3300-4e85-bf55-fe70e21b3e75.mov

## Confirmations

- [ ] I have chosen reviewers for my PR.
- [ ] I have assigned myself to this PR.
- [ ] I have chosen an appropriate label for the PR.
- [ ] I have completed the mandatory sections of this document.
- [ ] I have deleted any unused sections.
- [ ] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

File: packages/components/src/local/molecules/sortable-list/index.tsx [hunk 1]
```diff
@@ -124,6 +124,11 @@ export const SortableList: React.FC<PropTypes> = ({
           }
         }
       }
+      
+      if (!newValue) {
+        newValue = "New Role"
```
Comment (IanMayo) [inline packages/components/src/local/molecules/sortable-list/index.tsx]: Since we refer to "New Role" from two places, could you declare it as a global constant, please?  Then we won't have a logic break if one string gets changed but not the other.

Comment (sanjayradadiya) [reply packages/components/src/local/molecules/sortable-list/index.tsx]: Global constant declared for `New Role`

**Review by IanMayo — APPROVED** [review]
Approved.
