### PR TITLE
[SERGE-607] Fix channel tab not draggable

### LINKED ISSUE #607: Bug - we can't drag channels to re-arrange them
We can no longer drag channels to re-arrange them.

I guess this issue has arisen since we moved to a _Component_ based architecture, though it could be an emergent issue in `Flex Layout`.

### PR DESCRIPTION
**Pull request by zukilover**
## 🧰 Issue
Closes #607 

## 🤔 Reason: 
we can't drag channels to re-arrange them

## 🔨Work carried out:
- [x] Revert inccorect default channel configuration
- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

[Bug - we can't drag channels to re-arrange them](https://app.gitkraken.com/glo/card/d24fc84a65a24573a7530dad7e9dd04e)

### CODE REVIEW

File: packages/client/src/consts.js [hunk 1]
```diff
@@ -182,8 +182,7 @@ export const FLEX_LAYOUT_MODEL_DEFAULT = {
   global: {
     tabSetTabStripHeight: 45,
     tabEnableClose: false,
-    tabEnableRenderOnDemand: false,
-    tabEnableDrag: false
```
Comment (IanMayo) [inline packages/client/src/consts.js:186]: Well, that looks like a straightforward fix 🤣

**Review by IanMayo — APPROVED** [review]
Tested on Heroku deployment. Working fine.
