### PR TITLE
Fix issue style run time error

### LINKED ISSUE #1642: Runtime style error
In the debug console we're displaying a warning for `rcb` elements:
image

It doesn't really bother me, but it's cluttering the console.

Steps to reproduce:
* run wargame
* log into `small-wargame` as `White` - `Game Control`.
* click on an information marker
* warning appears on console

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1642

### CODE REVIEW

File: packages/components/src/local/form-elements/rcb/index.tsx [hunk 1]
```diff
@@ -16,10 +16,7 @@ const buildStyles = (options: any[]): any => {
   const opts = {}
   options.forEach((option, idx) => {
     opts[`root-${idx}`] = {}
```
Comment (IanMayo) [inline packages/components/src/local/form-elements/rcb/index.tsx:18]: well, I wasn't expecting it to be this simple 🤣 

Does the UI for this form still look ok @lebaphi  ?

Comment (lebaphi) [reply packages/components/src/local/form-elements/rcb/index.tsx:18]: Yep, it works fine @IanMayo but I see other error when loading the page on first time.

https://user-images.githubusercontent.com/26705621/176198455-3d4f1511-f731-4a8e-a916-ab086235de38.mov

Comment (IanMayo) [reply packages/components/src/local/form-elements/rcb/index.tsx:18]: Ok, I see a few errors:

* `Warning: Cannot update a component` - yes, it would be good to fix this.  I'll create an issue for it.
* `[Violation] 'message' handler` - I don't know much about this
* `HEAD http://localhost:3000/assets/couners/unk` - Yes, this may be an issue.  I'll investigate.

**Review by IanMayo — APPROVED** [review]
Issue resolved.
