### PR TITLE
Fix issue unread message count

### LINKED ISSUE #1204: Unread message count works incorrectly

### PR DESCRIPTION
**Pull request by lebaphi**
Fixes #1204

### CODE REVIEW

**Comment by IanMayo** [comment]
Hello @lebaphi - could you have another look at this PR, and resolve the conflicts please?

**Comment by lebaphi** [comment]
> Hello @lebaphi - could you have another look at this PR, and resolve the conflicts please?

sure @IanMayo, I resolve it now

**Comment by IanMayo** [comment]
Aah, this isn't quite done.  When the player marks a message as `unread` we need to regenerate the count of unread messages.

Or, maybe that's an unrelated issue 🤣 

screencast

**Comment by lebaphi** [comment]
> Aah, this isn't quite done. When the player marks a message as `unread` we need to regenerate the count of unread messages.
> 
> Or, maybe that's an unrelated issue 🤣
> 
> screencast

I think so, let me take a look at this :D

**Review by IanMayo — APPROVED** [review]
Working perfectly :-)

File: packages/components/src/local/coa-status-board/helpers/gen-data.tsx [hunk 1]
```diff
@@ -209,7 +209,7 @@ export const genData = (
     }
 
     const row: Row = {
-      id: message.message.Reference || message._id,
+      id: message._id || message.message.Reference,
```
Comment (IanMayo) [inline packages/components/src/local/coa-status-board/helpers/gen-data.tsx:212]: @lebaphi - do you know the reason for the above change?

All PouchDB documents have an `_id` field, so the `Reference` will never get used.  I _think_ the previous way was the correct way around.

Comment (lebaphi) [reply packages/components/src/local/coa-status-board/helpers/gen-data.tsx:212]: @IanMayo Ah I get it from the old code base, but the same with you, I think we should use `message._id` instead of the `message.message.Reference`.
image

I change it to make the row id is the same with the message id, then we can filter the opened message in the `ExpandedComponent` component.
