### PR TITLE
1656 wrong id for new message

### LINKED ISSUE #1656: New map messages produces wargame with wrong id
When a wargame update happens, the admin pages pull out the most recent wargame with a particular`doc_id` (`initial-settings` if pre-initiated, and `settings` if after initiated).

But, when I submit a message from the map (umpire laydown in this case) the new document is stored with a date-time id.

Then, when I make a wargame change from the admin pages (such as initiate wargame), they actually retrieve and modify an earlier wargame.

Steps to reproduce:
1. checkout branch `1656_wargame_document_id`
2. open `wargame-l56yw0y5.sqlite` database in DB Browser. Verify there are 3 records. Newest one is `initial_wargame`
3. note that this wargame includes the phrase "Umpire laydown" 4 times.
4. enter game `Small wargame-laydown`
5. login as `Game Control`
6. move 4 assets from "laydown pen". Click once to select, and once to drag.  Move them anywhere.
7.  Once all 4 are moved, "Submit laydown" button will become enabled. Click it, and confirm "Submit laydown"
8.  Open wargame database.  There are now 5 records. The two new ones are "Umpire Laydown" message, then new wargame. Note that the `doc_id` for the new wargame is the date/time. Also note that the new wargame doesn't include the phrase "Umpire laydown" - since no assets are still waiting for "umpire laydown"
9.  Open admin pages, enter `Small wargame-laydown`
10.  Mark wargame as initiated
11.  Player UI fails, since `Error: Should not have umpire laydown for initiated wargame`
12.  Look at database. It now has 6  records. The newest wargame has date-time for `doc_id`, and includes the phrase "umpire laydown" - which shows it wasn't the most recent wargame that got updated.

### LINKED ISSUE #1667: Background polygons not rendered
We have test data that includes regions of similarly styled polygons.

But, they're not shown in Storybook:
image

### PR DESCRIPTION
**Pull request by IanMayo**
Fixes #1656 
Fixes #1667

Supercedes #1666

### CODE REVIEW

File: packages/server/providers/pouchdb.js [hunk 1]
```diff
@@ -139,6 +138,26 @@ const pouchDb = (app, io, pouchOptions) => {
...
+
+    const db = new PouchDB(databaseName, pouchOptions)
+
+    db.find({
+      selector: {
+        messageType: INFO_MESSAGE,
+        _id: { $ne: wargameSettings }
+      },
+      limit: 1,
+      sort: [{ _id: 'desc' }]
```
Comment (IanMayo) [inline packages/server/providers/pouchdb.js:159]: hey @lilitkarapetyan  - this is clever :-)

But, I have this worry:
1.  Doesn't PouchDb have to sort all the documents by `_id` before it can determine the last one?

Comment (lilitkarapetyan) [reply packages/server/providers/pouchdb.js:159]: Hi Ian, From my research I found that the PouchDb doesn't give us to take last one, the best solution in this case just make sort and then take.
