### PR TITLE
fix clean copy bug

### LINKED ISSUE #827: Client crash on `Create clean copy`
A Game Control is trying to create a duplicate of a wargame from the Admin page.

The `Clean copy` process should copy a wargame, but delete all messages, and just have the wargame description, in a non-initiated state.  Note: Ian doesn't think the flaw is in this logic.

He used `Clean copy` from a wargame's context menu.

A blank screen was shown.

Here is the client-side error log:
image

There is a _chance_ that this issue is related to us starting to append `.sqlite` file suffix to wargames.  When we join a wargame as a player, or when we open a wargame for editing, then the correct filename is found.  But, when we run `Clean Copy` it fails.

Or, maybe... The duplicate wargame is created, but we try to access it before it is physically available.

### PR DESCRIPTION
**Pull request by lilitkarapetyan**
## 🧰 Issue

closes #827,  #830, #832

## 🤔 Reason: 

Fixed Clean Copy bug, but one more bug still there, same crash present for Duplicate

## 🔨Work carried out:

- [x] Tests pass

## Confirmations

- [x] I have chosen reviewers for my PR.
- [x] I have assigned myself to this PR.
- [x] I have chosen an appropriate label for the PR.
- [x] I have completed the mandatory sections of this document.
- [x] I have deleted any unused sections.
- [x] I confirm that I have checked for required README updates and acted accordingly.

### CODE REVIEW

**Review by IanMayo — CHANGES_REQUESTED** [review]
`Clean Copy` no longer crashes client.

But, the new copy can't be opened.

If I create a clean copy, and open the copy, the client crashes.  If I refresh the page, the new copy will open.
screencast

**Comment by IanMayo** [comment]
Hi, there's another issue. If I create a duplicate, I can't save changes to it.

I did `Duplicate`, then went into the new wargame. When I tried to save a change to the wargame title it threw this error:
image

File: packages/client/src/api/wargames_api/index.ts [hunk 1]
```diff
@@ -140,11 +140,11 @@ export const populateWargame = (): Promise<Wargame> => {
   return fetch(serverPath + 'allDbs')
     .then((response: Response): Promise<string[]> => response.json())
     .then((dbs: string[]) => {
-      const wargameNames: string[] = wargameDbStore.map((db) => db.name)
+      const wargameNames: string[] = wargameDbStore.map((db) => db.name)      
       const toCreateDiff: string[] = _.difference(dbs, wargameNames)
       const toCreate: string[] = _.pull(toCreateDiff, MSG_STORE, MSG_TYPE_STORE, SERGE_INFO, '_replicator', '_users')
 
-      toCreate.forEach((name) => {
+      toCreate.forEach((name, i) => {
```
Comment (IanMayo) [inline packages/client/src/api/wargames_api/index.ts]: @lilitkarapetyan - the `i` is unused. Should we delete it?
